### ISSUE TITLE
BSI环境变量规范化的问题

### ISSUE THREAD

**Issue by hank-sunday** [asiainfoLDP/datafactory#68]
当前BSI变量命名规则为 ```BSI_服务实例名_参数名```
这种情况下，如果不把服务实例名作为一个参数传递给DC，应用程序就很难判断到底应该读什么参数。
同样，如果绑定两个以上同样的服务，也无法进行服务类别的区分。
参考VCAP_SERVICES的方式，建议修改为：```BSI_服务名_服务实例名_参数名```
这样的话，应用程序可以根据服务名（可以通用一些，不是用户自己定义的名字）进行判断。多个同类型的服务也可以自动分组一起。

**Comment by zonesan** [comment]
好。改。

**Comment by zonesan** [comment]
Fixed with https://github.com/asiainfoLDP/datafactory/commit/3f066cf4afc1119dda6633d3e9210f055ebdc0c3
